### PR TITLE
Fix nonce issue for replay attack

### LINKED ISSUE #687: Replay Tx on another Chain
## Vulnerability Overview:

Since ethermint uses the same type of chainIDEpoch for ethereum compatibility, a verified signature in ethereum is still valid in ethermint with the same msg content and chainIDEpoch, which enables "cross-chain transaction replay" attack etc.

## Details and Root Cause:

First, we found some ground truths:

1. Both ethermint and ethereum have the same signature scheme.
2. User has the same public key and private key on ethermint and ethereum.
3. Different chainID can be parsed to a same chainIDEpoch such as "ethereum-1" and "erhermint-1"

Thus, if a msg successfully executed on ethereum of some chainIDEpoch, say 1 (mainnet), then it can be replaied on ethermint of the same chainIDEpoch (with the nonce check passed), and vice versa.

## Steps to Exploit:

1. Suppose that there are two chains. One's chainID is "Ethereum-1",the other is "Ethermint-1".The victim have accounts on both chains with the same public key (private key).
2. The victim transfer 10eth to the attacker,and the victim's MsgEthereumTx.data.nonce on "Ethereum-1" is 300. The victim's MsgEthereumTx.data.nonce on "Ethermint-1" is 300（or less than 300）.For the previously mentioned vulnerability can greatly reduce the difficulty of exploiting this vulnerability only need to meet the nonce of the replayed chain than the nonce of the replayed chain can be low.
4. The attacker replay the MsgEthereumTx on "Ethermint-1".

### PR DESCRIPTION
**Pull request by summerpro**
Closes: https://github.com/cosmos/ethermint/issues/687
- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/okex/okexchain/blob/develop/CONTRIBUTING.md#pr-targeting))

- [x] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/okex/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Review by AaronZgl — APPROVED** [review]

File: app/rpc/namespaces/eth/api.go [hunk 1]
```diff
@@ -1000,17 +1000,18 @@ func (api *PublicEthereumAPI) generateFromArgs(args rpctypes.SendTxArgs) (*evmty
...
-	}
-
+	// get the nonce from the account retriever and the pending transactions
+	nonce, err = api.accountNonce(api.clientCtx, args.From, true)
 	if err != nil {
 		return nil, err
 	}
 
+	if args.Nonce != nil {
+		if nonce != (uint64)(*args.Nonce) {
```
Comment (ilovers) [inline app/rpc/namespaces/eth/api.go:1010]: only need one if here?
```suggestion
		if args.Nonce != nil && (uint64)(*args.Nonce)  != nonce {
```

**Review by louisliu2048 — APPROVED** [review]

**Review by ilovers — APPROVED** [review]
