### PR TITLE
FIX: fix hd path to 'm/44'/996'/0'/0/0' in sdk.Config

### LINKED ISSUE #516: account generation misses hd.Path in `okexchaind testnet`
### 1. Describe
The account generation in `okexchaind testnet` misses hd.Path during the genesis file generation.

### 2. Impact
The same mnemonics points to different accounts.

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by RevelationOfTuring**
Close: #516 
- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/okex/okexchain/blob/develop/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/okex/coding/blob/master/README.md#merging-a-pr))

### CODE REVIEW

**Review by zhongqiuwood — APPROVED** [review]

File: app/types/config.go [hunk 1]
```diff
@@ -23,7 +23,8 @@ const (
 	Bech32PrefixConsPub = EthBech32Prefix + sdk.PrefixValidator + sdk.PrefixConsensus + sdk.PrefixPublic
 
 	// Bip44CoinType satisfies EIP84. See https://github.com/ethereum/EIPs/issues/84 for more info.
-	Bip44CoinType = 996
+	Bip44CoinType        = 996
+	BIP44HDPathOKExChain = "m/44'/996'/0'/0/0"
```
Comment (xiangjianmeng) [inline app/types/config.go:27]: Would it be better to assign ​​"m/44'/996'/0'/0/0" to variable BIP44HDPath?

**Review by xiangjianmeng — APPROVED** [review]
